name: Build Windows (MSYS2 MinGW64)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup MSYS2
        uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          update: true
          path-type: strict
          install: |
            mingw-w64-x86_64-toolchain
            git
            cmake
            ninja
            mingw-w64-x86_64-pkgconf
            mingw-w64-x86_64-gtk3
            mingw-w64-x86_64-glib2
            mingw-w64-x86_64-fftw
            mingw-w64-x86_64-matio
            mingw-w64-x86_64-libxml2
            mingw-w64-x86_64-libzip
            mingw-w64-x86_64-libusb
            mingw-w64-x86_64-zlib

      # （必要なら）MSYSパッケージの ntldd を別ステップで導入
      - name: Install ntldd (MSYS package)
        shell: msys2 {0}
        run: |
          pacman --noconfirm -S --needed ntldd-git

      - name: Build libiio
        shell: msys2 {0}
        run: |
          set -e
          git clone https://github.com/analogdevicesinc/libiio.git
          cd libiio
          mkdir build && cd build
          cmake -G Ninja -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/mingw64 ..
          ninja
          ninja install

      - name: Build iio-oscilloscope
        shell: msys2 {0}
        run: |
          set -e
          mkdir -p build && cd build
          cmake -G Ninja -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/mingw64 ..
          ninja
          ninja install

      - name: Package portable bundle
        shell: msys2 {0}
        run: |
          set -e
          DEST=/c/_pkg/iioosc
          mkdir -p $DEST/bin $DEST/plugins $DEST/share/glib-2.0/schemas

          # 本体EXE
          cp -f /mingw64/bin/iio-oscilloscope.exe $DEST/

          # 依存DLLを収集（ntlddを使う）
          ntldd -R /mingw64/bin/iio-oscilloscope.exe | awk '/mingw64/ {print $3}' | sort -u | xargs -I{} cp -u {} $DEST/bin/ || true

          # プラグインDLL（あなたのCMake設定でインストールされるもの）
          if [ -d /mingw64/bin/plugins ]; then
            cp -r /mingw64/bin/plugins/* $DEST/plugins/ || true
          fi

          # GTKのスキーマ
          cp -r /mingw64/share/glib-2.0/schemas/*.xml $DEST/share/glib-2.0/schemas/ || true
          glib-compile-schemas $DEST/share/glib-2.0/schemas || true

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: iio-oscilloscope-portable
          path: |
            C:\_pkg\iioosc\
